name: dfs
description: Dart Flutter Scripts (DFS) -- collection of useful scripts for Dart and Flutter projects. 
version: 0.0.1
homepage: https://github.com/osaxma

environment:
  sdk: '>=2.15.0 <3.0.0'


dependencies:
  analyzer: ^3.0.0
  code_builder: ^4.1.0
  dart_style: ^2.2.1
  path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
